name: PGUtils
version: '1.1.3'
main: com.github.pgutils.PGUtils
api-version: '1.20'
author: [Penchev, Ivan]
website: https://github.com/ivan100-ivoop/PGUtils
depend: [ProtocolLib]
#soft-depend: [TokenManager]


commands:
  pg:
    description: Reload the configuration.
    permission: pgutils.usage
    usage: "Usage: /pg <subcommand>"

permissions:
  pgutils.usage:
    permission-message: You do not have permission to use this command.
    default: op
  pgutils.join:
    permission-message: You do not have permission to use this command.
    default: op
  pgutils.leave:
    permission-message: You do not have permission to use this command.
    default: op
  pgutils.reload:
    permission-message: You do not have permission to use this command.
    default: op
  pgutils.bypass.commands:
    permission-message: You do not have permission to use this command.
